import Head from 'next/head'
import Moment from 'moment'
import { OnViewAnimation } from '../animations/OnViewAnimation'
import { getAllPosts, PostProps } from '../lib/post'

import {
  Container,
  PostList,
  Link,
  Post,
  Title,
  Description,
  Date,
} from '../styles/postsPage'

interface Props {
  allPosts: PostProps[]
}

const Posts = ({ allPosts }: Props) => {
  return (
    <>
      <Head>
        <title>Ryan Souza&apos;s Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Container>
        <h1>My posts</h1>
        <PostList>
          {allPosts.map((post, index) => (
            <Link href={`../post/${post.slug}`} key={index}>
              <OnViewAnimation>
                <Post>
                  <Title>{post.title}</Title>
                  <Description>{post.description}</Description>
                  <Date>{Moment(post.date).format('LL')}</Date>
                </Post>
              </OnViewAnimation>
            </Link>
          ))}
        </PostList>
      </Container>
    </>
  )
}

export default Posts

export const getStaticProps = async () => {
  const allPosts = getAllPosts(['title', 'date', 'slug', 'description'])

  return {
    props: { allPosts },
  }
}
